[tool.black]
line-length = 120
skip-string-normalization = '1'

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120

[tool.flake8]
ignore = ["DJ01", "W503", "E231", "E501", "E203", "E722", "F401", "W605", "F403"]
max-line-length = 120
ban-relative-imports = true
